changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: Hyphen
    name: openfeature-provider-go

  # If you want to add extra header/footer text in the release notes
  header: |
    ## OpenFeature Go Provider ({{ .Tag }})
  footer: |
    ## Thanks!
    For more information, please check the [README.md](README.md)

builds:
  - id: openfeature-provider-go
    skip: true
